version: 2.1

# orbs- reusable packages for use

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

# jobs- the set of instructions

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo  "Running tests..."
          npm run test

  publish:
    excecutor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build
        image: dakshajaan/ educational-space
      - docker/push:
          image: dakshajaan/ educational-space

  build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            echo "Building Docker image..."
            docker build -t dakshajaan/educational-space:appfordevopsv1 .
            docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
            docker push dakshajaan/educational-space:appfordevopsv1



workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
            
