version: 2.1

# orbs- reusable packages for use

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

# jobs- the set of instructions

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo  "Running tests..."
          npm run test

  publish:
    excecutor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: dakshajaan/educational-space
      - docker/push:
          image: dakshajaan/educational-space

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build

      # Mini activity
      - publish:
          requires:
            - test
